db:
  url: jdbc:h2:~/MeliChallenge;AUTO_SERVER=TRUE
  driver-class-name: org.h2.Driver
  username: sa
  password: 
h2:
  console:
    enabled: true
    path: /h2-console
server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 25
      min-spare: 2  
  servlet:
    context-path: /product-detail
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0  # 100% para endpoints de aplicación
    enabled: true  # 
zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
prometheus:
  metrics:
    export:
      enabled: true
      step: 30s
logging:
  level:
    '[io.micrometer.tracing]': WARN
    '[brave]': WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"